### ISSUE TITLE
Create a minified/built js file consumable by the browser

### ISSUE THREAD

**Issue by adonespitogo** [alexsasharegan/browser-http-client#2]

**Comment by alexsasharegan** [comment]
If I made a bundle, the only way to consume the bundle is in a context that won't give you any type completions. I think that really defeats the purpose of this client—making strongly typed http requests possible.

Can you tell me more about your use case? If you're looking to just get up and going with ajax requests, why not just use `fetch` or drop in `axios`? This lib shines when you work with it in typescript. Without it, I guess it's conveniently small, but probably overly complex due to the type _safer_ control flow.

**Comment by alexsasharegan** [comment]
Closing for house keeping. I'll reopen if a compelling use case is provided.
